# http://edge.wasmcloud.akadns99.net:8080/?origin=https://contentcredentials.org/_app/immutable/assets/home1.33703fa3.jpg&width=800

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: poprox
  annotations:
    version: v0.0.4
    description: 'Provenance over Proxy'
spec:
  components:
    - name: http-component
      type: component
      properties:
        # To use the locally compiled code in this folder, use the line below instead after running `wash build`:
        # image: file://./build/http_hello_world_s.wasm
        image: oci-registry.akamaized.net/adobe/poprox:0.1.0
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1
            spread: []
        - type: link
          properties:
            target: httpclient
            namespace: wasi
            package: http
            interfaces: [outgoing-handler]
        # Link the component to the local NATS server
        - type: link
          properties:
            target: nats-msg
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]

    # Add a capability provider that enables HTTP access
    - name: httpserver
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-server:0.22.0
      traits:
        # Link the httpserver to the component, and configure the HTTP server
        # to listen on port 8080 for incoming requests
        - type: link
          properties:
            target: http-component
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
            source_config:
              - name: default-http
                properties:
                  address: 0.0.0.0:8080
        - type: spreadscaler
          properties:
            replicas: 1
            spread: []

    - name: httpclient
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-client:0.12.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread: []

    - name: poprox-s3
      type: component
      properties:
        # To use the locally compiled code in this folder, use the line below instead after running `wash build`:
        # image: file://./build/http_hello_world_s.wasm
        image: oci-registry.akamaized.net/adobe/poprox_s3:0.1.0
        config:
          - name: bucket-config
            properties:
              bucket: cosmonic-document-demo
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            replicas: 1
            spread: []
        - type: link
          properties:
            target: nats-msg
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]
        # Link to the blobstore provider which provides the underlying storage interface
        #
        # Establish a unidirectional link to the `blobstore-fs` (the filesystem-powered blobstore provider),
        # so the `poprox-s3` component can make use of blobstore functionality provided by the filesystem
        # (i.e. reading/writing blobs)
        - type: link
          properties:
            target: blobstore-s3
            namespace: wasi
            package: blobstore
            interfaces: [blobstore]
    # Add a capability provider that implements `wasmcloud:messaging` using NATS
    - name: nats-msg
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:0.22.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread: []
        - type: link
          properties:
            target: poprox-s3
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
            source_config:
              - name: nats-subscription
                properties:
                  subscriptions: poprox.>|poprox_queue
    # Capability provider that exposes a blobstore with the filesystem
    - name: blobstore-s3
      type: capability
      properties:
        # To use a locally compiled provider, uncomment the line below
        # (and ensure that you've used `wash par crate` to create the par file below)
        #
        # image: file://../../../../crates/provider-blobstore-fs/provider-blobstore-fs.par.gz
        image: ghcr.io/wasmcloud/blobstore-s3:0.9.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread: []
    # - name: blobstore-s3
    #   type: capability
    #   properties:
    #     image: ghcr.io/wasmcloud/blobstore-fs:0.8.0
    #   traits:
    #     - type: spreadscaler
    #       properties:
    #         replicas: 1
    #         spread: []