apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: wasmcloud-banking
  annotations:
    app: banking
  labels:
    wasmcloud.dev/generated-by: wash-dev
spec:
  # policies:
  #   - name: nats-kv
  #     type: policy.secret.wasmcloud.dev/v1alpha1
  #     properties:
  #       backend: nats-kv
  components:
    - name: api
      type: component
      properties:
        image: file:///Users/brooks/github.com/brooksmtownsend/banking-demo/build/banking-app_s.wasm
        # secrets:
        #   - name: client_id
        #     properties:
        #       policy: nats-kv
        #       key: client_id
        #   - name: client_secret
        #     properties:
        #       policy: nats-kv
        #       key: client_secret
      traits:
        - type: spreadscaler
          properties:
            instances: 100
        - type: link
          properties:
            namespace: wasi
            package: http
            interfaces:
              - outgoing-handler
            target:
              name: http-client
    - name: http-server
      type: capability
      properties:
        image: file:///Users/brooks/github.com/brooksmtownsend/banking-demo/wasmcloud.banking/providers/http-router/build/http-router.par.gz
        config:
          - name: wasi-http-config
            properties:
              port: '8000'
              theme: 'banking'
      traits:
        - type: link
          properties:
            target: api
            namespace: wasi
            package: http
            interfaces: [incoming-handler]
    - name: http-client
      type: capability
      properties:
        image: ghcr.io/wasmcloud/http-client:0.12.1
