# syntax=docker/dockerfile:1
FROM cgr.dev/chainguard/wolfi-base:latest

# libstdc++ is needed by ollama to run, ldconfig is from:
# https://github.com/wolfi-dev/os/issues/16863
RUN <<EOF
apk add --no-cache libstdc++ ollama
ldconfig
EOF

RUN <<EOF
/bin/sh -c "ollama serve &"
sleep 3
ollama run llava ''
EOF