
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-setup
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 45
  template:
    spec:
      initContainers:
        - name: wait-for-it
          image: chainguard/wait-for-it:latest
          args:
            - ollama:11434
            - --timeout=15
            - --strict
      containers:
      - name: setup-ollama
        image: chainguard/curl:latest
        args:
          - ollama:11434/api/pull
          - -d
          - '{"name": "llava"}'
      restartPolicy: OnFailure