---
apiVersion: v1
kind: Service
metadata:
  name: http-router
spec:
  selector:
    host-label.k8s.wasmcloud.dev/workload: provider
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer