apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: nats-secondary
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.10.18
    helm.sh/chart: nats-1.2.2
  name: nats-external
  namespace: default
spec:
  selector:
    app.kubernetes.io/component: nats
    app.kubernetes.io/instance: nats-primary
    app.kubernetes.io/name: nats
  ports:
  - appProtocol: tcp
    name: nats
    port: 4222
    protocol: TCP
    targetPort: nats
  - appProtocol: tcp
    name: leafnodes
    port: 7422
    protocol: TCP
    targetPort: leafnodes
  - appProtocol: http
    name: websocket
    port: 4223
    protocol: TCP
    targetPort: websocket
  sessionAffinity: None
  type: LoadBalancer